### ISSUE TITLE
Single Quotes vs Double Quotes

### ISSUE THREAD

**Issue by dfagan2** [sumcoding/svg-to-js-cli#3]
The first time I ran this, it output `null` for each of the width, height, and viewBox properties. I found that it was due to those attributes being defined with single quotes in the SVG's. Changing them to double quotes fixed it.

While double quotes is more standard for an SVG, it might be a non-starter for projects that have opinionated linter/formatters that require single quotes. So would be great to support both.

**Comment by sumcoding** [comment]
Fixed in 11869ced4196269886efec418c25383e94f20e52
